accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import login_view, logout_view, RegisterView, ProfileView, ProfileUpdateView, PasswordChangeView

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', RegisterView.as_view(), name='signup'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('profile/change_password/', PasswordChangeView.as_view(), name='password_change'),
]

source/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('C_and_C.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.


class CustomUser(AbstractUser):
    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
    )
    POSITION_CHOICES = (
        ('student', 'Student'),
        ('worker', 'Worker'),
        ('seller', 'Seller')
    )

    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    position = models.CharField(max_length=20, choices=POSITION_CHOICES)
    seller_file = models.FileField(upload_to='vendor_files/', blank=True)
    is_seller = models.BooleanField(default=False)
    is_seller_mode = models.BooleanField(default=False)

    def __str__(self):
        return self.username


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='profile', null=False,
                                blank=False)
    bio = models.TextField(null=True, blank=True, default="No Bio")
    number = models.CharField(max_length=20, null=True, blank=True)
    avatar = models.ImageField(null=True, blank=True, upload_to='avatars/')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Date of Birth')

    def __str__(self):
        return f'{self.user.get_full_name()}'

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from accounts.models import Profile, CustomUser


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label='Password', required=True, strip=False)
    password_confirm = forms.CharField(widget=forms.PasswordInput(), label='Confirm Password', required=True,
                                       strip=False)
    seller_file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': False}), required=False)

    STATUS_CHOICES = (
        ('student', 'Student'),
        ('worker', 'Worker'),
        ('seller', 'Seller')
    )
    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
    )
    position = forms.ChoiceField(choices=STATUS_CHOICES, widget=forms.RadioSelect(), label='Position', required=False)
    gender = forms.ChoiceField(widget=forms.RadioSelect(), label='Gender', choices=GENDER_CHOICES, required=False)

    def clean(self):
        cleaned_data = super().clean()
        # username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        position = cleaned_data.get('position')
        seller_file = cleaned_data.get('seller_file')

        if position == 'seller':
            if not seller_file:
                raise forms.ValidationError("Seller position requires uploading a confirmation file.")

        if position == 'seller' and password == password_confirm and seller_file:
            pass

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Passwords must match')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    class Meta:
        model = CustomUser
        fields = (
            'username', 'password', 'password_confirm',
            'first_name', 'last_name', 'email', 'position', 'seller_file', 'gender'
        )


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email')
        labels = {'email': 'Email', 'first_name': 'First Name', 'last_name': 'Last Name'}

        widgets = {'email': forms.EmailInput(attrs={'class': 'form-control w-50'}),
                   'first_name': forms.TextInput(attrs={'class': 'form-control w-50'}),
                   'last_name': forms.TextInput(attrs={'class': 'form-control w-50'}), }


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)
        labels = {'bio': 'Bio', 'avatar': 'Avatar', 'number': 'Number', 'birth_date': 'Birth date'}
        widgets = {'bio': forms.Textarea(attrs={'class': 'form-control w-50', 'rows': 3}),
                   'avatar': forms.FileInput(attrs={'class': 'form-control w-50'}),
                   'number': forms.NumberInput(attrs={'class': 'form-control w-50'}),
                   'birth_date': forms.DateInput(attrs={'class': 'form-control w-50', 'type': 'date'})}


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Password',
                               strip=False)
    password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                       label='Password Confirm', strip=False)
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Old password',
                                   strip=False)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Password don't match")

        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get("old_password")

        if not self.instance.check_password(old_password):
            raise forms.ValidationError("Old password is incorrect")

        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ('old_password', 'password', 'password_confirm')

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User

from C_and_C.models import Request
from .forms import *
from .models import Profile


# Create your views here.

@csrf_exempt
def login_view(request):
    context = {}
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            next = request.POST.get('next')
            if next:
                return redirect(next)
            return redirect('shops')
        else:
            context['message'] = "Invalid username or password"

    return render(request, 'accounts/login.html', context=context)


# @csrf_exempt
@login_required
def logout_view(request):
    logout(request)
    return redirect('shops')


class RegisterView(generic.CreateView):
    model = get_user_model()
    template_name = 'accounts/signup.html'
    form_class = RegisterForm

    def form_valid(self, form):
        user = form.save()

        if form.cleaned_data.get('position') == 'seller' and form.cleaned_data.get('seller_file'):
            request = Request.objects.create(user=user,topic='Is Seller', document=form.cleaned_data.get('seller_file'))
            print(request)

        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        return 'shops'


class ProfileView(generic.DetailView):
    model = get_user_model()
    template_name = 'accounts/profile.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        return context

    def get_object(self, queryset=None):
        return self.request.user


class ProfileUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    template_name = 'accounts/profile_edit.html'
    context_object_name = 'user_object'
    form_class = UserUpdateForm

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
            # print(kwargs)
        return super().get_context_data(**kwargs)

    def get_profile_form(self):
        profile_form = {'instance': self.object.profile}
        if self.request.method == 'POST':
            profile_form['data'] = self.request.POST
            profile_form['files'] = self.request.FILES
        return ProfileUpdateForm(**profile_form)

    def get_success_url(self):
        return reverse('profile')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()

        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return render(context)

    def get_object(self, queryset=None):
        return self.request.user


class PasswordChangeView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    form_class = PasswordChangeForm
    template_name = 'accounts/change_password.html'
    context_object_name = 'user_obj'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse('login')

templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="l-form">
            <div class="shape1"></div>
            <div class="shape2"></div>

        <div style="display: flex; flex-direction: row;">
            <img src="{% static 'img/university.png' %}" alt="" id="img_uni">
        </div>
            <div class="row justify-content-center mt-5" style="margin-top: 200px">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <h1 class="card-title text-center">Change Password</h1>
                            {% include 'partials/user_form.html' with form_method='POST' %}
                        </div>
                    </div>
                </div>
            </div>

    </div>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <div class="l-form">
            <div class="shape1"></div>
            <div class="shape2"></div>
{#            {{ message }}#}

        <div style="display: flex; flex-direction: row;">
            <img src="{% static 'img/university.png' %}" alt="" id="img_uni">
        </div>
    <div class="main_login">
            <div class="form" id="login_form">
{#                <img src="{% static 'img/donut.gif' %}" width="70px" id="donut"/>#}
{#                <img src="{% static 'img/sandwich.gif' %}" width="70px" id="sandwich"/>#}

                <img src="{% static 'img/person1.jpg' %}" width="200px" id="person1"/>
                <img src="{% static 'img/person2.jpg' %}" width="230px" id="person2"/>

                 <form action="{% url 'login' %}?next={{ request.GET.next }}" method="POST" class="form-content">
                    <h1 class="form__title">Welcome</h1>
                    <div class="form__div form__div-one">
                        <div class="form__icon">
                            <i class='bx bx-user-circle'></i>
                        </div>

                        {% for error in form.non_field_errors %}
                            <p class="text-danger">{{ error }}</p>
                        {% endfor %}

                        <div class="form__div-input">
{#                            <label for="username" class="form__label">Username</label>#}
                            <input type="text" class="form__input" name="username" placeholder="Username">
                        </div>
                    </div>

                    <div class="form__div">
                        <div class="form__icon">
                            <i class='bx bx-lock' ></i>
                        </div>

                        <div class="form__div-input">
{#                            <label for="password" class="form__label">Password</label>#}
                            <input type="password" class="form__input" name="password" placeholder="Password">
                        </div>
                    </div>
                    <p class="text-danger">{{ message }}</p>
                    <a href="#" class="form__forgot">Forgot Password?</a>

                    <input type="submit" class="form__button" value="Login">
                 <div style="text-align: center" class="mb-4">
                     <a href="{% url 'signup' %}" class="text-center">Do no have an account?</a>
                     </div>

                    <div class="form__social">
                        <span class="form__social-text">Our login with</span>

                        <a href="#" class="form__social-icon"><i class='bx bxl-facebook' ></i></a>
                        <a href="#" class="form__social-icon"><i class='bx bxl-google' ></i></a>
                        <a href="#" class="form__social-icon"><i class='bx bxl-instagram' ></i></a>
                    </div>
                </form>
            </div>
    </div>

        </div>
        <script src='{% static 'js/main.js' %}'></script>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="l-form">
    <div class="shape1"></div>
    <div class="shape2"></div>

    <div style="display: flex; flex-direction: row;">
        <img src="{% static 'img/university.png' %}" alt="" id="img_uni">
    </div>
    <h2 class="text-center">Profile</h2>

    <div class="d-flex justify-content-center">
        <div class="card2">
            <div class="additional">
                <div class="user-card">
                    <div class="level center">{{ user_obj.position|default:'User' }}</div>
                    <div class="points center">0 Points</div>
                    <div class="avatar">
                        {% if user_obj.profile.avatar %}
                            <img src="{{ user_obj.profile.avatar.url }}" alt="avatar" >
                            {% elif user_obj.gender == 'male'%}
                                <img src="{% static 'img/student.png' %}" alt="">
                            {% elif user_obj.gender == 'female'%}
                                <img src="{% static 'img/student(1).png' %}" alt="">
                            {% else %}
                                <img src="{% static 'img/blocked.png' %}" alt="">
                        {% endif %}
                    </div>
                </div>
                <div class="more-info" style="text-align: center">
                    <h1>{{ user_obj.first_name }} {{ user_obj.last_name }}</h1>
                    <div class="coords mt-3">
                        <strong>Username:</strong>
                        {% if user_obj.username %}
                        <span>{{ user_obj.username }}</span>
                        {% else %}
                        <span class="text-warning">Not declared</span>
                        {% endif %}
                    </div>
                    <div class="coords mt-3">
                        <strong>First Name:</strong>
                        {% if user_obj.first_name %}
                        <span>{{ user_obj.first_name }}</span>
                        {% else %}
                        <span class="text-warning">Not declared</span>
                        {% endif %}
                    </div>
                    <div class="coords mt-3">
                        <strong>Last Name:</strong>
                        {% if user_obj.last_name %}
                        <span>{{ user_obj.last_name }}</span>
                        {% else %}
                        <span class="text-warning">Not declared</span>
                        {% endif %}
                    </div>
                    <div class="coords mt-3">
                        <strong>Number:</strong>
                        {% if user_obj.profile.number %}
                        <span>{{ user_obj.profile.number }}</span>
                        {% else %}
                        <span class="text-warning">Not declared</span>
                        {% endif %}
                    </div>
                    <div class="coords mt-3">
                        <strong>Birth Date:</strong>
                        {% if user_obj.profile.birth_date %}
                        <span>{{ user_obj.profile.birth_date }}</span>
                        {% else %}
                        <span class="text-warning">Not declared</span>
                        {% endif %}
                    </div>
                    <div class="stats">
                        <div>
                            <div class="title">Awards</div>
                            <i class="fa fa-trophy"></i>
                            <div class="value">0</div>
                        </div>
                        <div>
                            <div class="title">Matches</div>
                            <i class="fa fa-gamepad"></i>
                            <div class="value">0</div>
                        </div>
                        <div>
                            <div class="title">Pals</div>
                            <i class="fa fa-group"></i>
                            <div class="value">123</div>
                        </div>
                        <div>
                            <div class="title">Coffee</div>
                            <i class="fa fa-coffee"></i>
                            <div class="value infinity">∞</div>
                        </div>
                    </div>
                </div>
            </div>
            <div style="text-align: center">
                <h1>{{ user_obj.username }}</h1>
                <p>Bio: {{ user_obj.profile.bio }}</p>
                <span class="more">Mouse over the card for more info</span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="l-form">
    <div class="shape1"></div>
    <div class="shape2"></div>

    <div style="display: flex; flex-direction: row;">
        <img src="{% static 'img/university.png' %}" alt="" id="img_uni">
    </div>


    <div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <h2 class="text-center mt-3">Profile Edit</h2>
                <div class="card-body">
                    <form action="{% url 'profile_edit' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'partials/user_form.html' with form=form fields_only=True %}
                        {% include 'partials/user_form.html' with form=profile_form fields_only=True %}
                        <button type="submit" class="btn btn-outline-success mt-3">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

</div>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="l-form">
    <div class="shape1"></div>
    <div class="shape2"></div>
    <div style="display: flex; flex-direction: row;">
        <img src="{% static 'img/university.png' %}" alt="" id="img_uni">
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-lg" id="signup" style="height: 80vh; overflow-y: auto;">
                    <div class="card-body">
                        <h1 class="text-center mb-4">Registration</h1>
                        <form action="{% url 'signup' %}?next={{ request.GET.next }}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% for error in form.non_field_errors %}
                                    <p>Error while doing:</p>
                                    <p class="alert alert-danger">{{ error }}</p>
                                {% endfor %}
                                {% for error in form.errors %}
                                        <p>Error while doing:</p>
                                        <p class="alert alert-danger">{{ error }}</p>
                                {% endfor %}

                                <div class="form-group mb-3">
                                    <label for="id_username">Username:</label>
                                    <input type="text" name="username" id="username" class="form-control">
        {#                            {{ form.username }}#}
                                </div>

                                <div class="form-group mb-3">
                                    <label for="id_password">Password:</label>
                                    <input type="password" name="password" id="password" class="form-control">
        {#                            {{ form.password }}#}
                                </div>

                                <div class="form-group mb-3">
                                    <label for="id_password_confirm">Password Confirm:</label>
                                    <input type="password" name="password_confirm" id="password_confirm" class="form-control">
        {#                            {{ form.password_confirm }}#}
                                </div>

                                <div class="form-group mb-3">
                                    <label for="id_first_name">First Name:</label>
                                    <input type="text" name="first_name" id="first_name" class="form-control">
        {#                            {{ form.first_name }}#}
                                </div>

                                <div class="form-group mb-3">
                                    <label for="id_last_name">Last Name:</label>
                                    <input type="text" name="last_name" id="last_name" class="form-control">
        {#                            {{ form.last_name }}#}
                                </div>

                                <div class="form-group mb-3">
                                    <label for="id_email">Email:</label>
                                    <input type="text" name="email" id="email" class="form-control">
        {#                            {{ form.email }}#}
                                </div>

                                <div class="form-group mb-3">
                                    <label for="id_position">Position:</label><br>
                                    <div class="form-check form-check-inline">
                                        <input type="radio" name="position" id="id_position_student" value="student" class="form-check-input">
                                        <label for="id_position_student" class="form-check-label">Student</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input type="radio" name="position" id="id_position_worker" value="worker" class="form-check-input">
                                        <label for="id_position_worker" class="form-check-label">Worker</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input type="radio" name="position" id="id_position_seller" value="seller" class="form-check-input">
                                        <label for="id_position_seller" class="form-check-label">Seller</label>
                                    </div>
                                </div>

                                <div class="form-group mb-3">
                                    <label for="id_position">Gender:</label><br>
                                    <div class="form-check form-check-inline">
                                        <input type="radio" name="gender" id="id_gender_male" value="male" class="form-check-input">
                                        <label for="id_gender_male" class="form-check-label">Male</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input type="radio" name="gender" id="id_gender_female" value="female" class="form-check-input">
                                        <label for="iid_gender_female" class="form-check-label">Female</label>
                                    </div>
                                </div>


                            <div class="form-group" id="sellerform">
                                    <input type="checkbox" id="seller">
                                    <p id="pseller">I am an Seller</p>
                            </div>


                                <div class="form-group" id="documentation" style="display: none">
                                    <label for="" class="text-danger" >You need to upload the documentation confirming that you are the seller! <p class="text-primary" id="see_more">Know more.</p></label>
                                        <div class="input-group mb-3">
                                            <label class="input-group-text" for="fileToUpload">Choose file</label>
                                            <input type="file" name="seller_file" id="seller_file" class="form-control">
                                        </div>
                                </div>
                                <button type="submit" class="btn btn-outline-success btn-block mt-4">Register</button>
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/main.js' %}"></script>
{% endblock %}