source/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('C_and_C.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

C_and_C/models.py
from django.db import models
from django.contrib.auth import get_user_model


# Create your models here.


class Shop(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    location = models.CharField(max_length=100, null=False, blank=False)
    owner = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, null=False, blank=False, related_name='shops')
    image = models.ImageField(upload_to='shop_images/', null=True, blank=True)

    def __str__(self):
        return f"Shop: {self.name}"


class Category(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE , null=False, blank=False, related_name='products')
    cost = models.IntegerField(null=False, blank=False)
    ingredients = models.CharField(max_length=100, null=True, blank=True)
    image = models.ImageField(upload_to='product_images/', null=True, blank=True)
    number = models.IntegerField(null=True, blank=True, default=1)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=False, related_name='products')

    def __str__(self):
        return f"{self.name} Ingredients: {self.ingredients}"


class Order(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, null=False, blank=False, related_name='orders')
    date = models.DateTimeField(auto_now_add=True)
    total = models.IntegerField(null=True, blank=True)
    is_ready = models.BooleanField(default=False)
    in_the_process = models.BooleanField(default=False)

    def __str__(self):
        return f'Order - {self.id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    shop = models.ForeignKey(Shop, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"Order: {self.order}, Product: {self.product}, Shop: {self.shop}, Quantity: {self.quantity}"


class Request(models.Model):
    SHOP_CREATION = 'Shop Creation'
    SHOP_DELETE = 'Shop Delete'
    IS_SELLER = 'Is Seller'
    OTHER_TOPIC = 'Other Topic'

    TOPIC_CHOICES = [
        (SHOP_CREATION, 'Shop Creation'),
        (SHOP_DELETE, 'Shop Delete'),
        (IS_SELLER, 'Is Seller'),
    ]
    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, null=False, blank=False,
                             related_name='requests')
    topic = models.CharField(max_length=100, choices=TOPIC_CHOICES, default=SHOP_CREATION)
    description = models.TextField(null=True, blank=True)
    document = models.FileField(upload_to='request_documents/', null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    refused = models.BooleanField(default=False)
    used = models.BooleanField(default=False)
    shop = models.ForeignKey(Shop, on_delete=models.SET_NULL, null=True, blank=True, related_name='requests')

templates/orders/my_order.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="specialty section container">
    <a href="#" onclick="history.back()" class="form-control w-25 mb-3" id="go-back">Go back</a>
    {% if request.user.position == 'seller' and request.user.is_seller and request.user.is_seller_mode %}
        <p class="d-inline-flex gap-1">
              <a class="btn btn-outline-success ml-5 mr-5" data-bs-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">Incoming orders</a>
            <a href="" style="width: 320px" ></a>
              <button class="btn btn-outline-secondary ml-5 mr-5" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample2" aria-expanded="false" aria-controls="multiCollapseExample2">Done orders/Past orders</button>
              <button class="btn btn-outline-primary ml-5 mr-5" type="button" data-bs-toggle="collapse" data-bs-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2">Get two of them</button>
            </p>
            <div class="row">
              <div class="col">
                <div class="collapse multi-collapse" id="multiCollapseExample1">
                      <div class="specialty__container mb-3">
                      {% if not orders_for_shop%}
                        <p class="form-control alert-warning ">There is no incoming orders</p>
                    {% endif %}
                            {% for order in orders_for_shop %}
                            <div class="card mb-3" style="width: 18rem;">
                              <div class="card-body">
                                <h5 class="card-title">Order Id: {{ order.id }}</h5>
                                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                              </div>
                              <ul class="list-group list-group-flush">
                                  {% for order_item in order.orderitem_set.all %}
                                    <li class="list-group-item">{{ order_item.product.name }} - {{ order_item.shop.name }} - {{ order_item.quantity }}</li>
                                  {% endfor %}
                              </ul>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Total cost: {{ order.total }}
                                    <p class="alert-warning form-control" style="margin-left: -10px">Status: Waiting / In process</p>
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="order_pk" value="{{ order.pk }}">
                                        <input type="hidden" name="new_status" value="ready">
                                        <button type="submit" class="btn btn-outline-success">Mark as Ready</button>
                                    </form>
                                </li>
                            </ul>
                            </div>
                            {% endfor %}
                        </div>
                  </div>
              </div>


              <div class="col">
                <div class="collapse multi-collapse" id="multiCollapseExample2">
                {% if not orders_for_shop_done %}
                    <p class="form-control alert-warning">There is no past orders</p>
                {% endif %}
                      <div class="specialty__container mb-3">
                            {% for order in orders_for_shop_done %}
                            <div class="card mb-3" style="width: 18rem;">
                              <div class="card-body">
                                <h5 class="card-title">Order Id: {{ order.id }}</h5>
                                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                              </div>
                              <ul class="list-group list-group-flush">
                                  {% for order_item in order.orderitem_set.all %}
                                    <li class="list-group-item">{{ order_item.product.name }} - {{ order_item.shop.name }} - {{ order_item.quantity }}</li>
                                  {% endfor %}
                              </ul>
                              <ul class="list-group list-group-flush">
                                <li class="list-group-item">Total cost: {{ order.total }}
                                    <p class="alert-success form-control" style="margin-left: -10px">Status: Done</p>
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="order_pk" value="{{ order.pk }}">
                                        <input type="hidden" name="new_status" value="not_ready">
                                        <button type="submit" class="btn btn-outline-danger">Mark as Not Ready</button>
                                    </form>
                                </li>
                            </ul>
                            </div>
                            {% endfor %}
                        </div>
                </div>
              </div>
            </div>
    {% else %}
        <p class="d-inline-flex gap-1">
              <a class="btn btn-outline-success ml-5 mr-5" data-bs-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">Waiting orders</a>
            <a href="" style="width: 340px" ></a>
              <button class="btn btn-outline-secondary ml-5 mr-5" type="button" data-bs-toggle="collapse" data-bs-target="#multiCollapseExample2" aria-expanded="false" aria-controls="multiCollapseExample2">Done orders/Past orders</button>
              <button class="btn btn-outline-primary ml-5 mr-5" type="button" data-bs-toggle="collapse" data-bs-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2">Get two of them</button>
            </p>
            <div class="row">
              <div class="col">
                <div class="collapse multi-collapse" id="multiCollapseExample1">
                      <div class="specialty__container mb-3">
                      {% if not waiting_orders %}
                        <p class="form-control">There is no waiting orders</p>
                    {% endif %}
                            {% for order in waiting_orders %}
                            <div class="card mb-3" style="width: 18rem;">
                              <div class="card-body">
                                <h5 class="card-title">Order Id: {{ order.id }}</h5>
                                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                              </div>
                              <ul class="list-group list-group-flush">
                                  {% for order_item in order.orderitem_set.all %}
                                    <li class="list-group-item">{{ order_item.product.name }} - {{ order_item.shop.name }} - {{ order_item.quantity }}</li>
                                  {% endfor %}
                              </ul>
                              <ul class="list-group list-group-flush">
                                <li class="list-group-item">Total cost: {{ order.total }}
                                    <p class="alert-warning form-control" style="margin-left: -10px">Status: Waiting / In process</p>
                                </li>
                            </ul>
                            </div>
                            {% endfor %}
                        </div>
                  </div>
              </div>
              <div class="col">
                <div class="collapse multi-collapse" id="multiCollapseExample2">
                {% if not done_orders %}
                    <p class="form-control">There is no past orders</p>
                {% endif %}
                      <div class="specialty__container mb-3">
                            {% for order in done_orders %}
                            <div class="card mb-3" style="width: 18rem;">
                              <div class="card-body">
                                <h5 class="card-title">Order Id: {{ order.id }}</h5>
                                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                              </div>
                              <ul class="list-group list-group-flush">
                                  {% for order_item in order.orderitem_set.all %}
                                    <li class="list-group-item">{{ order_item.product.name }} - {{ order_item.shop.name }} - {{ order_item.quantity }}</li>
                                  {% endfor %}
                              </ul>
                              <ul class="list-group list-group-flush">
                                <li class="list-group-item">Total cost: {{ order.total }}
                                    <p class="alert-success form-control" style="margin-left: -10px">Status: Done</p>
                                </li>
                            </ul>
                            </div>
                            {% endfor %}
                        </div>
                </div>
              </div>
            </div>
    {% endif %}


    </div>


{% endblock %}